### ISSUE TITLE
[Map Edit Page] Map navigation & Fullscreen button checkboxes aren't working properly

### ISSUE THREAD

**Issue by bwstefano** [EarthJournalismNetwork/jeo-plugin#109]
Nothing happens when I check or uncheck the map navigation checkbox. The Fullscreen button checkbox is having the opposite behavior (button should appear when checkbox is selected, but is doing the opposite) at the map editor page

**Comment by pamelars86** [comment]
This bug was solved in #100 but is not available in the test environment yet. We need to update it.
