### ISSUE TITLE
[ Layer Interactions Modal ] Show that title is  mandatory and change onhover behavior. Update grid

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#128]
**To do**
- [x] Mark title as mandatory field
- [x]  In a map with interactions, when the mouse is over the point of the interaction, the info box must appear at the right corner of the map instead of mini popup. (see image below)
![image](https://user-images.githubusercontent.com/12487823/86435089-842fc300-bcd5-11ea-9895-7ee6f28a9ccc.png)

- [x] In a map with interactions, verify if when the mouse clicks on the point of the interaction, the mini popup appears as usual. Also, add a "x" to close the popup (see image below)
![image](https://user-images.githubusercontent.com/12487823/86435123-9578cf80-bcd5-11ea-8b0a-3f1c739dbae4.png)
- [x] add a "ok" button fixed in header

**Comment by icarooliv** [comment]
we should be able to achieve this by adding this following css to jeo-map.css

```
.jeomap .popup .mouseover, .mapboxgl-popup{
    transform:none !important;
    top: 10%;
    left: 90%;
}

.jeomap .popup .mouseover, .mapboxgl-popup-anchor-top .mapboxgl-popup-tip,
.mapboxgl-popup-anchor-bottom .mapboxgl-popup-tip,
.mapboxgl-popup-anchor-center .mapboxgl-popup-tip,
.mapboxgl-popup-anchor-left .mapboxgl-popup-tip,
.mapboxgl-popup-anchor-right .mapboxgl-popup-tip,
.mapboxgl-popup-anchor-bottom-right .mapboxgl-popup-tip,
.mapboxgl-popup-anchor-bottom-left .mapboxgl-popup-tip,
.mapboxgl-popup-anchor-top-right .mapboxgl-popup-tip, 
.mapboxgl-popup-anchor-top-left .mapboxgl-popup-tip{
    display:none !important;
}
```
and conditionally add these classes to mapbox.js 
```
const popUp = new mapboxgl.Popup( {
	className: 'jeo-popup',  // here
	closeButton: type === 'click',
	closeOnClick: true,
} );
```
