### ISSUE TITLE
[Mapa embed] The embed map must be full width

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#129]
- [x]  The embed map must be full width
![image](https://user-images.githubusercontent.com/12487823/85566515-7fe51500-b606-11ea-93ee-2c4d74cbb754.png)

![image](https://user-images.githubusercontent.com/12487823/85566543-86738c80-b606-11ea-875a-35a3ec449ddd.png)

Reference for embed map with all width
![image](https://user-images.githubusercontent.com/12487823/86987706-0d7b4580-c16d-11ea-9ea1-e1ee2137c786.png)

**Useful links**
https://github.com/EarthJournalismNetwork/jeo-plugin/blob/develop/src/includes/class-jeo.php#L216

**Reference**
https://infoamazonia.org/pt/maps/portugues-covid19-na-amazonia-02/#!/story=post-15457&full=true

COMMENT
https://news.mongabay.com/2020/11/peru-prosecutors-probe-amazon-deforestation-linked-to-mennonite-communities/
Esse aqui é um exemplo de matéria publicada pelo parceiro que vai usar o mapa. Se o mapa ficar legal na largura completa do post, então não precisa corrigir esta questão antes do lançamento. Mas teria que ser prioridade porque vai afetar outros embeds que temos em outros sites.

**Comment by isaquemelo** [comment]
**`feature/embed`**
