### ISSUE TITLE
[ Layer Editor ] Layer type = tilelayer produces error due to http

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#138]
![image](https://user-images.githubusercontent.com/12487823/85736157-9f4a7380-b6d4-11ea-80be-1894c46e7af6.png)

This layer type works if the layer's URL is https in jeo.hacklab.com.br
or if the site's url that is using the jeo plugin is http:
![image](https://user-images.githubusercontent.com/12487823/85739606-51833a80-b6d7-11ea-84c7-c9cc3a9c50f3.png)

**Comment by brunosmartin** [comment]
all layers must have https
