### ISSUE TITLE
[ Map Editor ] Sometimes, map shows post pins although "related all posts" is unchecked and error in categories/tags

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#139]
**Bug 1: _Map show all post pins although 'related all posts' is uncheked_**
![image](https://user-images.githubusercontent.com/12487823/85760909-a7141300-b6e8-11ea-98a7-6f2ddbd7f68f.png)

![image](https://user-images.githubusercontent.com/12487823/85761671-5e108e80-b6e9-11ea-81d6-def9ff1aca4a.png)

**Bug 2: _Related post section shouldn't allow users to create new categories or tags_**
 Encontramos um problema que está acontecendo com o plugin e que não havia acontecido até agora nos ambientes de homologação, mas está no dev. Veja só o relato da Ju, que eu confirmei:

![image](https://user-images.githubusercontent.com/12487823/93918243-6ecda200-fce2-11ea-8193-ed61812184c7.png)

Adicionei a tag “Amazônia Sufocada” nos posts como combinamos mas, ao tentar acrescentar essa tag no “related posts” do mapa dá erro.

Depois de digitar a tag no campo, ela parece como “NaN” e não me permite mais remover (tentei outras tags q já existiam, como “queimadas”, “fire”, “deforestation”, e acontece a mesma coisa). Se tento dar update, aparece erro - prints em anexo.

Se volto para a versão anterior, o campo volta a ficar vazio mas o problema persiste se tento acrescentar qualquer tag.

A única possibilidade de tag que ele me sugere como já existente, e portanto consigo adicionar, são #TierradeResistentes, #MaderaSucia e um outro “2 milliones de hectáreas”.

Adicionei o #TierradeResistentes como related posts no mapa e dei update mas nenhuma camada de histórias apareceu sobre o mapa. Ou seja, não está funcionando.

![image](https://user-images.githubusercontent.com/12487823/93918376-9f154080-fce2-11ea-8237-7cd90222c895.png)

![image](https://user-images.githubusercontent.com/12487823/93918475-c8ce6780-fce2-11ea-8890-82b141df254d.png)

### Proposal: Refactor this functionality

![image](https://user-images.githubusercontent.com/12487823/100892294-ef560f00-3498-11eb-8b14-f91f5eacc7ef.png)

1) Se o check 'Use related post' NÃO estiver marcado, não deve aparecer nenhum post no mapa

2) Se  o check 'Use related post' estiver marcado, aparecem os filtros
**Filtros**
Mesmo funcionamento do que o bloco newspack 'Homepage posts'
Se os campos estiverem vazios, mostra todos os posts
É possível só selecionar categorías/tags existentes
Não é permitido criar novas categorias ou tags

Similar ao bloco home posts de newspack
![image](https://user-images.githubusercontent.com/12487823/96169668-e2855800-0ef8-11eb-8188-3d6706f95c11.png)

TESTS

- [x] User can't create new categories in "Related Post" section in Map Editor
- [x] User can't create new tags in "Related Post" section in Map Editor
- [x] If 'use related post' is unchecked, no post is shown in map
- [x] If 'use related post' is checked without filters, all posts are shown in map
- [x] Stylized pins
Filters:
- [x] If 'use related post' is checked with filter "category", posts having that category are shown
- [x] If 'use related post' is checked with filter "tag", posts having that tag are shown
- [x] If 'use related post' is checked with filter "category" and "tag", posts having that category/tag are shown
- [x] If 'use related post' is checked with filter "start date", posts with publication date >= start date are shown
- [x] If 'use related post' is checked with filter "end date", posts with publication date <= end date are shown
- [x] If 'use related post' is checked with filter "start date" and "end date", posts between those dates are shown

**Comment by isaquemelo** [comment]
**feature/related-content-refractoring**
