### ISSUE TITLE
[ Published Map ] Each map must control its own legend block

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#166]
Steps to reproduce this bug
- User adds more than 1 map. Example: Map "A" and Map "B" (both with legends and layers blocks)
- User wants to open legend block from Map "A" only. However, Legend block from Map "A" and "B" are opened.

![image](https://user-images.githubusercontent.com/12487823/89220466-fe3eba80-d5a7-11ea-9e01-33123ab5efc7.png)

**Comment by isaquemelo** [comment]
branch **feature/map-action-icons**
