### ISSUE TITLE
[ Embed map ] Add footer to the map. Also it should include the external source's logo

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#167]
Example:
https://infoamazonia.org/pt/embed/?map_id=51947&width=960&height=480

![image](https://user-images.githubusercontent.com/12487823/98367902-2c072580-2015-11eb-95fa-727212d91ba0.png)

**Comment by isaquemelo** [comment]
Branch **`feature/embed`**

**Comment by pamelars86** [comment]
If the site doesnt have logo, a white block is appearing

![image](https://user-images.githubusercontent.com/12487823/98707393-c1305400-235e-11eb-8e73-a09a0c072517.png)

**Comment by pamelars86** [comment]
![image](https://user-images.githubusercontent.com/12487823/98721432-8e428c00-236f-11eb-8dad-d56577afe7c4.png)
só o box na parte de trás q tem opacidade, o logo mesmo está com 100%
o box tem 75% de opacidade
