### ISSUE TITLE
Admin - geocode posts: allow multiple primary and multiple secondary points

### ISSUE THREAD

**Issue by leogermani** [EarthJournalismNetwork/jeo-plugin#17]

**Comment by leopiccionia** [comment]
I've added some CSS to it. Some of them may be controversial -- e.g. ellipsing autocomplete results --, so let me know any needed improvements.

**Comment by leogermani** [comment]
Nice! Looking good!

I think it would be better if the list stayed on the left and the map control on the right. THe modal could be wider. Now it's bad having to scroll down and up all the time to edit the pins

**Comment by leopiccionia** [comment]
I've been fixing some JS bugs, and I've made some significant changes to layout: the map and the markers list are moved into tabs, and the markers on the map are now selectable. These changes make the markers list and map almost equivalent views for the same data (deleting markers is still only possible via the list).

In my experience, it makes the experience of adding geolocalization to a post more agile and enjoyable, but I'd like to know other perspectives.

If this path is approved, I'd like to make those tabs' styling more consistent with other modals' (possibly refactoring the related CSS into a separate component that wraps Gutenberg's native tabs).

**Comment by leogermani** [comment]
Looks nice,

The only thing I miss is some feedback when you drag and drop a marker. When the list was visible, you could see the address changing.

But overall is fine.

one thing left:

- [ ] Change the "Open Modal" button label on the sidebar

**Comment by leopiccionia** [comment]
Fixed them.
