### ISSUE TITLE
[ Mapbox styles ] Raster layer in Mapbox styles are rendered with black background

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#175]
**New bug**
aqui está uma situação em que o fundo fica preto com um style com duas camada raster, em que ambas são essenciais e não tem o que remover.
https://dev.infoamazonia.org/wp-admin/post.php?post=16257&action=edit&lang=en
https://studio.mapbox.com/styles/infoamazonia/ckfg4a1ev1j5219pp1b028k6q/

![image](https://user-images.githubusercontent.com/12487823/97350874-cb872400-186f-11eb-9f6d-74d446adfd77.png)

### **OLD BUG**
**O QUE ACONTECE? Workaround: Satellite layer in mapbox was removed**
Bug: Mapa com layer transparente. Essa layer "Amazonia Sufocada - 7 dias" é para ter o mesmo comportamento que a layer na issue #162 
Layer: https://dev.infoamazonia.org/wp-admin/post.php?post=83813&action=edit&lang=pt-pt
O Style no Mapbox: https://studio.mapbox.com/styles/infoamazonia/ckfej40b20c0f19mkrelmmy53/edit/#9.49/-6.9008/-55.4613
Um dos tilesets que são estilizados no Style: https://studio.mapbox.com/tilesets/infoamazonia.amzsufocada-7d/

**Teste do Stefano**
Editor Mapa : https://dev.infoamazonia.org/wp-admin/post.php?post=83825&action=edit&lang=pt-pt
Post publicado: https://dev.infoamazonia.org/pt-pt/maps/amazonia-sufocada-teste-stefano/

![image](https://user-images.githubusercontent.com/12487823/94061570-f0ddc980-fdbb-11ea-83b3-cec1f4d05c63.png)

![image](https://user-images.githubusercontent.com/12487823/94061496-d86daf00-fdbb-11ea-8973-d16785f7b52e.png)

De acordo ao Stefano, pode ser porque essa layer esta sendo renderizada como uma Raster. mas precisamos pesquisar como foi resolvido aquela outra layer colorido da issue #162 

Mapa com a layer em questão, aparece um erro na console
https://dev.infoamazonia.org/pt-pt/maps/amazonia-sufocada/
![image](https://user-images.githubusercontent.com/12487823/94693017-98518380-0309-11eb-8cb7-249a11e89a08.png)

**OUTROS COMENTÁRIOS**
Outro problema é que uma camada com interatividade neste mapa não mostra popups onclick e dá erro no console. O mapa deste screenshot é este: https://dev.infoamazonia.org/wp-admin/post.php?post=83825&action=edit&lang=pt-pt
(um teste que criei com as mesmas camadas do anterior para avaliar)

![image](https://user-images.githubusercontent.com/12487823/94014910-92482980-fd82-11ea-8958-20d66fc6feb1.png)

![image](https://user-images.githubusercontent.com/12487823/94014956-a1c77280-fd82-11ea-84e5-9f50d12bbf4c.png)

Você também vai notar que este mapa tem camadas com transparência que, no final, estão com fundo preto. Será por serem styles sobre styles? Me lembro do Leo Germani ter problemas em usar styles sobre styles, mas não sei se envolvia isso.
Aqui os links para uma das duas camadas deste mapa que deveriam ter fundo transparente:
No WordPress: https://dev.infoamazonia.org/wp-admin/post.php?post=83813&action=edit&lang=pt-pt
O Style no Mapbox: https://studio.mapbox.com/styles/infoamazonia/ckfej40b20c0f19mkrelmmy53/edit/#9.49/-6.9008/-55.4613
Um dos tilesets que são estilizados no Style: https://studio.mapbox.com/tilesets/infoamazonia.amzsufocada-7d/

E, por último, o embed de qualquer um destes dois mapas mostra que o mapa não possui camadas: https://dev.infoamazonia.org/embed/?map_id=83825

**Comment by pamelars86** [comment]
Testei no ambiente de produção infoamazonia e a layer em questão gerou o erro

![image](https://user-images.githubusercontent.com/12487823/94105225-3677b200-fe0f-11ea-9893-e50e5bf9b7a9.png)

![image](https://user-images.githubusercontent.com/12487823/94105178-1cd66a80-fe0f-11ea-9098-630766e772a8.png)

![image](https://user-images.githubusercontent.com/12487823/94105119-f87a8e00-fe0e-11ea-85c4-95e10f0d4db6.png)

**Comment by pamelars86** [comment]
Alguns links
https://docs.mapbox.com/mapbox.js/example/v1.0.0/stylelayer/

**Comment by bwstefano** [comment]
> Testei no ambiente de produção infoamazonia e a layer em questão gerou o erro

@pamelars86, no ambiente de produção do InfoAmazonia não é possível adicionar camadas do Mapbox porque o JEO ali usa uma API antiga. Desta forma, só adicionamos os tilesets, cujos IDs funcionam como os mapas antes da existência dos Styles, nos tempos do TileMill e Mapbox Classic. A única forma de adicionar um style é através das URLs tilelayers XYZ.

**Comment by pamelars86** [comment]
O Stefano criou uma cópia da layer no Mapbox Studio para nossos testes
https://studio.mapbox.com/styles/infoamazonia/ckfpgyno512d819pp75dqs8c1/edit/#4.52/-6.7/-58.14

**Comment by pamelars86** [comment]
**Descobertas 28/10**
- Os static tiles de um style só podem ser obtidos em jpg de acordo à documentação [aqui](https://docs.mapbox.com/api/maps/#static-tiles)

Retrieve 512x512 pixel or 256x256 pixel raster tiles from a Mapbox Studio style. The returned raster tile will be a JPEG
![image](https://user-images.githubusercontent.com/12487823/97580458-1ae56580-19d2-11eb-8f7e-518ba8504e71.png)

O mapbox-styles com problema esta usando um source de tipo raster que tem as imagens (dos tiles)
![image](https://user-images.githubusercontent.com/12487823/97581837-d6f36000-19d3-11eb-9f23-8463ec234fc6.png)

Quando tem alguma layer do tipo raster dentro do studio ele retorna um jpg e não um png.


O problema sempre vai acontecer se vc usar uma raster layer no mapbox que é "incompleta" - que não tem todos os tiles (que deixam lacunas), e que esses espaços faltantes não são preenchidos por nenhuma outra layer dentro do mapbox studio.
Nas layers do tipo raster geralmente todos os tiles estão presentes (todas as imagenzinhas), a não ser que essa layer seja empilhada com outra que feche as lacunas (imagens) faltantes abaixo dela

![image](https://user-images.githubusercontent.com/12487823/97582286-5123e480-19d4-11eb-8ff0-0f83c713765d.png)

É como se a layer elevation do exemplo tivesse sem algumas imagens
E deixasse a de baixo aparecer
Mas e se a de baixo tiver lacunas?
Dai o preto aparece
Pq o mapbox nos retorna o resultado dessas layers (os static tilesets) em jpg se tiver alguma layer do tipo raster dentro, presumindo suponho eu que vc vai criar uma raster completinha

Solução no mapbox studio
**Adicionar um base map porque o ele cobriria/completaria aquelas lacunas.**

**Comment by bwstefano** [comment]
Eu vejo que são dois problemas distintos que levam o fundo preto a aparecer. Um é este, detalhado no [comentário acima](#issuecomment-718766206). De acordo com ele, o problema destas camadas raster é que, como são chamadas usando a [Static Tiles API](https://docs.mapbox.com/help/glossary/static-tiles-api/), o resultado retornado é composto por imagens JPG. Dúvida: por qual motivo optamos por esta API ao invés da [Raster Tiles API](https://docs.mapbox.com/help/glossary/raster-tiles-api/), que [suporta solicitar camadas raster em formato PNG](https://docs.mapbox.com/api/maps/#retrieve-raster-tiles)? Me parece que a grande diferença é que as camadas raster teriam que ser chamadas diretamente, e não como parte de um style. Seria bom saber a visão do @isaquemelo aqui.

O outro problema, não abordado pelo comentário, é o que tivemos com outros styles que possuíam camadas raster como "mapbox-satellite" ocultas e apresentavam fundo preto. Elas só deixaram de apresentar fundo preto quando a camada oculta foi excluída do style.
