### ISSUE TITLE
[ Story Map ] Apply slide'preview automatically after changing slide

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#187]
- [x] Por que não fazer de uma forma em que a troca de slides já leva ao local do slide desejado no mapa, sem precisar clicar em “Preview”?
- [x] No StoryMap Publicado: Quando faço o scroll para frente as layers sao renderizadas corretamente. Contudo, se eu faço o scrull para trás, tem layers que não sao carregadas

**Comment by isaquemelo** [comment]
1- Feature: **feature/auto-slide-preview**
2 - Bugfix: **bugfix/storymap-scroll-view**
