### ISSUE TITLE
[ Published Map ] Use Icons in JEO Map when layers/legends block are minimized in mobile mode

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#200]
- [x] Use Icons in JEO Map when layers/legends block are minimized in mobile mode
![image](https://user-images.githubusercontent.com/12487823/97045956-070eaf00-154d-11eb-854a-dee71086f6f4.png)

**Comment by isaquemelo** [comment]
We can't put them close to each other without changing the HTML structure. So I just changed the icon visual.

**Comment by isaquemelo** [comment]
**feature/map-action-icons**

**Comment by pamelars86** [comment]
Some comments:

- If the "Legends block" has several layers' legend, those legends and the info button are not shown correctly:

![image](https://user-images.githubusercontent.com/12487823/102018352-864d8180-3d4b-11eb-8489-91c31c01f749.png)
