### ISSUE TITLE
[ Story Map ] Fix zoom buttons of navigate map in responsive mode (and other responsive bugs)

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#210]
- [x] Fix how zoom buttons are shown in mobile
![image](https://user-images.githubusercontent.com/12487823/97863163-50959180-1ce5-11eb-8ff6-4d3b082a2d51.png)

- [x] Layer / Legend icons with new behavior in responsive mode (adjust "back to top" position)
Test with layers and legends:
![image](https://user-images.githubusercontent.com/12487823/102018470-30c5a480-3d4c-11eb-81f9-c0a1e38c1b0f.png)

**Comment by hockpond** [comment]
![image](https://user-images.githubusercontent.com/39286044/104051411-d858ba00-51c6-11eb-98a4-6af971ae48f4.png)
![image](https://user-images.githubusercontent.com/39286044/104051479-f0c8d480-51c6-11eb-8286-e34ce430991f.png)

it seems to be ok
