### ISSUE TITLE
[ Discovery ] Add a validation if a layer is private, don't render it

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#216]
**Steps to reproduce**
1. Create a map with a private layer
2. Go to Discovery Page -> map tab
3. An error occurs in console

![image](https://user-images.githubusercontent.com/12487823/98683614-01cea400-2344-11eb-882c-b6eabf6f9482.png)

**Comment by isaquemelo** [comment]
Fix na develop
