### ISSUE TITLE
[ Map Editor ] First layer mustn't have editable dropdown

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#217]
**Steps to reproduce error:**
1. Create a public layer
2. Add this layer to a map (add more layers)
3. Edit layer's visibility in 1) to private
4. Back to map's editor page in 2), the private layer doesnt' appear in Selected layer. However, the 1st layer appears with editable dropdown.

![image](https://user-images.githubusercontent.com/12487823/98680030-9c78b400-233f-11eb-83e6-70c412be94bd.png)

- [x] First layer mustn't have editable dropdown
- [x] After fixing the previous item, verify that error above doesn't occurs anymore
Às vezes o seletor de camadas não permite reordená-las. Erro no console: "Uncaught TypeError: _this.ghostRef.current is null". Exemplo: https://dev.infoamazonia.org/wp-admin/post.php?post=90073&action=edit. Atualizar a página resolveu o problema.

**Bug related to this issue**
O primeiro, que não é urgente, parece ser um bug neste mapa que a Ju está editando. Vejo que, por algum motivo, o tipo do base layer passou a ser editável, quando deveria ser sempre "fixed" – https://dev.infoamazonia.org/wp-admin/post.php?post=83689&action=edit

![image](https://user-images.githubusercontent.com/12487823/94014813-6c228980-fd82-11ea-83a7-62e98132dee8.png)

**o que deveria acontecer?**
Quando fizer o drag and drop, a 1eira layer sempre deveria dizer  "Base layer should be fixed"
![image](https://user-images.githubusercontent.com/12487823/94047035-e580a300-fda7-11ea-83ee-4ea59a1e4547.png)

**Comment by pamelars86** [comment]
Stefano:
22. Eu já vi este comportamento outras vezes: na seleção de camadas foi possível selecionar o tipo da camada da base. Nesta, que é tradução de uma camada, isto acontece: https://dev.infoamazonia.org/wp-admin/post.php?post=90081&action=edit
--

![image](https://user-images.githubusercontent.com/12487823/101358803-22721700-387a-11eb-9454-2afab490ca3a.png)

**Comment by isaquemelo** [comment]
Partialy solved in #247. A new filter may be necessary.

**Comment by isaquemelo** [comment]
The branch **bugfix/private-layers** uses fixes applied in **bugfix/edit-layer-settings-crash**. So **bugfix/edit-layer-settings-crash** should be tested first.

**Comment by isaquemelo** [comment]
If a map is created with some layers, and one of those goes private. When the map page is refreshed it won't show up in the list anymore. And, if the private layer was the base layer the next one after it, will become the new base layer.
