### ISSUE TITLE
[ Layer Editor ] Add an optional name for legend

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#218]
![image](https://user-images.githubusercontent.com/12487823/98687917-09dd1280-2349-11eb-8478-beded145981f.png)

Example
![image](https://user-images.githubusercontent.com/12487823/98687958-15c8d480-2349-11eb-9305-8428e708ef55.png)

Other items
- [x] legends and layers blcoks with same width
- [x] icon for legends block

![image](https://user-images.githubusercontent.com/12487823/98952861-b4386f80-24da-11eb-8518-a5217b5fa94e.png)

**Comment by isaquemelo** [comment]
Branch `**feature/legend-title**`

**Comment by isaquemelo** [comment]
![image](https://user-images.githubusercontent.com/7103838/98716196-eaa2ad00-2369-11eb-8e3a-d9ab2a71e759.png)
![image](https://user-images.githubusercontent.com/7103838/98716289-132aa700-236a-11eb-9de8-c05b44f39a40.png)
