### ISSUE TITLE
[ Interactions ] Hover is not working correctly

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#237]
Interação de tipo Hover
Não muda o hover
Problema do cursor: trocar de seta para mão

https://dialogochino.net/wp-content/uploads/2019/10/MapaPecuaria_en.html

Mais um teste: se eu coloco uma interação on hover, o popup só mostra a primeira feature navegada. As demais só vão ser exibidas se eu passar com o mouse fora de uma feature com hover. 
https://dev.infoamazonia.org/maps/teste-de-mapa-com-base-e-uma-interatividade/

**Comment by isaquemelo** [comment]
**bugfix/change-style-selection**
