### ISSUE TITLE
[ Map Editor - Layers ] Change checkboxes 'load as style' to radiobutton. Change Label 'load interactions'

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#238]
Após da avaliação do Stefano, sairam os seguintes combinados:
- Passar o checkbox para o radiobutton, porque o comportamento de misturar layers não funciona bem (limitação mapbox)
- Label 'Load as style'-> 'Load interactions'

**Comment by isaquemelo** [comment]
branch `bugfix/change-style-selection`
