### ISSUE TITLE
[ Published Map ] Mapbox credit must appear on maps

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#245]
**1) An example of map with layer without source**
Here, the Mapbox credit is appearing correctly
https://infoamazonia-jeo.hacklab.com.br/maps/mapa-pink/

![image](https://user-images.githubusercontent.com/12487823/101167472-b3e24e80-3618-11eb-9f73-e2b144602795.png)

**2) Bug:** 
Mapbox credit is not appearing on map when some layers have 'source'. An example [here](https://dev.infoamazonia.org/maps/ativistas-ambientais-assassinados-em-2014/)

![image](https://user-images.githubusercontent.com/12487823/101166205-a926ba00-3616-11eb-8ad2-74190fc31ba0.png)

**3) Fix: Mapbox credit and layer's source**

![image](https://user-images.githubusercontent.com/12487823/101170611-78964e80-361d-11eb-913e-d978910091ff.png)

Stefano implemented it on this site:
https://dialogochino.net/wp-content/uploads/2019/10/MapaPecuaria_en.html

**Comment by isaquemelo** [comment]
![Screenshot from 2020-12-09 15-36-12](https://user-images.githubusercontent.com/7103838/101672372-8d674d80-3a34-11eb-8912-e5c46749415d.png)
![Screenshot from 2020-12-09 15-36-07](https://user-images.githubusercontent.com/7103838/101672377-8f311100-3a34-11eb-9769-ce6d745afd95.png)

**Comment by isaquemelo** [comment]
**bugfix/mapboxcredit**
