### ISSUE TITLE
[ Discovery ] The link shared to email must have the sidebar (stories, maps  and social links)

### ISSUE THREAD

**Issue by isaquemelo** [EarthJournalismNetwork/jeo-plugin#250]
- Não deve incluir o "/embed/"
Tem que ser tipo assim:
https://infoamazonia-jeo.hacklab.com.br/discovery/?discovery=true&selected-layers=[]&zoom=0&center=0

Linha que deve ser modificada:
https://github.com/EarthJournalismNetwork/jeo-plugin/blob/master/src/js/src/discovery/index.js#L233

**Comment by pamelars86** [comment]
É preciso integração da URL com o Sidebar

**Comment by isaquemelo** [comment]
branch **feature/sidebar-url**
