### ISSUE TITLE
[ Carto ] Allow user to configure frequency to update all layers: daily, weekly, monthly. Option in JEO Settings

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#271]

**Comment by isaquemelo** [comment]
branch **feature/carto-update-interval**

**Comment by isaquemelo** [comment]
Use plugin WP Crontrol to take a look at the crons 
![image](https://user-images.githubusercontent.com/7103838/103901548-0b705000-50d8-11eb-8655-b6be0814c33e.png)

**Comment by pamelars86** [comment]
**Stefano's comment:**

Carto - Configuração da frequência de atualização
Se o usuário trocar esta configuração, quando a próxima atualização é feita? Ou seja, se eu trocar de um intervalo diário para semanal ou mensal, a próxima atualização será só em 7 ou 30 dias? Ou é definida um dia do mês ou da semana e o usuário vai ter que esperar este dia chegar para que a atualização seja feita? Ou logo que o usuário faz a troca, tudo é atualizado e o relógio passa a contar a partir desta mudança?

Seria bom fazer esse esclarecimento, que poderia talvez vir de uma linha de texto do tipo "a próxima atualização será realizada na data DD/MM/YYYY às HH:MM" junto desta configuração. Ou só uma explicação da mecânica de atualização junto.
