### ISSUE TITLE
[ Map Editor ] input in textboxs for Zoom level is not working correctly 

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#278]
- [ ] Ainda tenho problemas para controlar o zoom máximo e mínimo do mapa usando a caixa de texto
![image](https://user-images.githubusercontent.com/12487823/102799346-2aa97680-4391-11eb-98e7-673be855d055.png)

**Comment by isaquemelo** [comment]
It was a Gutenberg issue, after testing using WP5.7 worked like a charm https://github.com/WordPress/gutenberg/issues/25018

**Comment by isaquemelo** [comment]
Besides that, I did a quick fix in `develop`  that refers to when a clean env is created creating a error if the default map zoom is not set

**Comment by willowmagrini** [comment]
@isaquemelo relato do @bwstefano : durante os testes Usando o Firefox, eu tive dificuldades em testar esta correção. Sempre que digitei nas caixas de texto, e só depois de fazer isso, não consegui editar mais nenhum texto da página, mesmo na área de edição do post (como título ou descrição do mapa). No console, o erro abaixo apareceu. No Chrome este problema não ocorre.

Uncaught (in promise) InternalError: too much recursion
Te https://dev.infoamazonia.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146
Pg https://dev.infoamazonia.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
unstable_runWithPriority https://dev.infoamazonia.org/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25
Da https://dev.infoamazonia.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
Pg https://dev.infoamazonia.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61
ha https://dev.infoamazonia.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60
Ja https://dev.infoamazonia.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224
ch https://dev.infoamazonia.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:93
e https://dev.infoamazonia.org/wp-includes/js/dist/data.min.js?ver=943087ae96d075f126df689839bb96b9:2
t https://dev.infoamazonia.org/wp-includes/js/dist/data.min.js?ver=943087ae96d075f126df689839bb96b9:2
react-dom.min.js:146:173

**Comment by isaquemelo** [comment]
@willowmagrini nenhuma correção foi adicionada para esse problema, o fix vem do próprio WP como relatei acima. 
A unica coisa que foi mudada foi aqui https://github.com/EarthJournalismNetwork/jeo-plugin/commit/858ef980429ca5c5ed7c89f03e1cdbe1f343780c que não tem relação com o problema relatado acima.

No entanto, testei no firefox aqui e o problema aconteceu, fiz alguma pesquisa e vi que o problema foi introduzido no WP5.7. 
Fiz o downgrade para o WP5.6.2 e o problema não aconteceu mais

**Comment by willowmagrini** [comment]
@bwstefano no infoamazonia me parece ok, podemos fechar essa issue?
