### ISSUE TITLE
[ Edit Layer ] Bugs in Edit Interactions / Legends

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#283]
- [x] After clicking on "Edit Interactions", an error appears. It happens with this specific layer  [here](https://dev.infoamazonia.org/wp-admin/post.php?post=100549&action=edit)

![image](https://user-images.githubusercontent.com/12487823/104217069-a8edbb80-5419-11eb-9ff1-123144b05eb0.png)

![image](https://user-images.githubusercontent.com/12487823/104216945-7d6ad100-5419-11eb-9cb4-1f434f3351e1.png)

I tested with other layers, and edit interactions button works correctly. I commented that with Stefano and he answered:
**_Stefano's comment:_**
_Este Style estava quebrado no Mapbox porque os tilesets foram renomeados. Depois eu ajustei o Style e atualizei. Não deve ser questão de cache porque agora todas as camadas do Style aparecem normalmente. Eu tentaria duplicar este Style e chamar o Style resultante numa outra camada do JEO para ver o que acontece._

- [x] If user fills legend's info, then he/she closes and opens the legend section, info isn't saved completly.

Example: I added some colors in barscale, but when I closed and opened the legend section, those colores weren't saved

![image](https://user-images.githubusercontent.com/12487823/104217446-2a454e00-541a-11eb-9844-2f683af79fa6.png)

![image](https://user-images.githubusercontent.com/12487823/104217460-2dd8d500-541a-11eb-9db5-2998c0993568.png)

**Comment by isaquemelo** [comment]
Fix 1: **bugfix/mapbox-layer-without-source**

**Comment by isaquemelo** [comment]
Fix 2: **bugfix/legend-panel-toggle** 

This second fix requires the retest of all legend types
