### ISSUE TITLE
[ Discovery / Share ] Stories tab must be opened instead of maps tab

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#292]
- [x] Stories tab must be opened instead of maps tab

**Currently:**
URL link [here](https://dev.infoamazonia.org/en/discovery/?share=true&selected-layers=%5B%5B99530%2C99538%5D%2C%5B99458%2C99538%5D%2C%5B99523%2C99538%5D%5D&zoom=7&center=%7B%22lng%22%3A-77.33485380000002%2C%22lat%22%3A-1.4858225999999917%7D)
![image](https://user-images.githubusercontent.com/12487823/104591639-bc806880-564b-11eb-93d4-e037fc66527c.png)

- [x] Social network links must have the same URL as URL Icon and Email

Ex. https://dev.infoamazonia.org/discovery-pt/?share=true&selected-layers=%5B%5B89967%2C99318%5D%2C%5B23640%2C99318%5D%2C%5B17466%2C99318%5D%2C%5B89978%2C99318%5D%5D&zoom=4.4971057297744315&center=%7B%22lng%22%3A-54.78229713682617%2C%22lat%22%3A-13.692480713652486%7D

**Comment by isaquemelo** [comment]
Branch: **bugfix/discovery-share**. PR: https://github.com/EarthJournalismNetwork/jeo-plugin/pull/300

**Comment by pamelars86** [comment]
Discovery created by me :

![image](https://user-images.githubusercontent.com/12487823/104645430-ce82fb00-568d-11eb-8aac-c2fb48057dbb.png)


Discovery using URL icon:
It includes stories! 
![image](https://user-images.githubusercontent.com/12487823/104645491-de9ada80-568d-11eb-908b-56e47123709b.png)
