### ISSUE TITLE
[ Published Map] Credit icon is not appearing correctly

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#293]
- [x] O ícone "i" do crédito do mapa está aparecendo assim (ver [aqui](https://infoamazonia-jeo.hacklab.com.br/maps/indice-de-progresso-social-na-amazonia/)):

![image](https://user-images.githubusercontent.com/12487823/104529779-42b79300-55e9-11eb-9053-501b80c22b6c.png)

![image](https://user-images.githubusercontent.com/12487823/104530666-36ccd080-55eb-11eb-8388-dea4028f3c9c.png)

- [x] In embed map, the icon credit and the logo are not appearing correctly: [here](https://infoamazonia-jeo.hacklab.com.br/embed/?map_id=985). 

![image](https://user-images.githubusercontent.com/12487823/104530578-038a4180-55eb-11eb-859e-aa069e7561c3.png)

Suggestion: Site's logo could be below map. 

![image](https://user-images.githubusercontent.com/12487823/104530805-90cd9600-55eb-11eb-9956-80a5bd8f69f5.png)

Also, is possible to upload logo for embed map in JEO Settings? Because, logo could be white so it would be over a white background as Ekuatorial's site (example [here](https://ekuatorial.iesech.info/embed/?map_id=67030))

![image](https://user-images.githubusercontent.com/12487823/104531047-0d607480-55ec-11eb-876e-176d1ea42fef.png)

- [x] Discovery embed: Mapbox is adding its own watermark and it is over site's logo:

![image](https://user-images.githubusercontent.com/12487823/103902140-df090380-50d8-11eb-9bb5-d37fa0e9c5d9.png)

**Comment by isaquemelo** [comment]
Fix of the overlaping "i": https://github.com/EarthJournalismNetwork/jeo-plugin/pull/299

**Comment by isaquemelo** [comment]
Add embed footer logo setting: https://github.com/EarthJournalismNetwork/jeo-plugin/pull/298

**Comment by isaquemelo** [comment]
The embed footer position change can be followed by https://github.com/EarthJournalismNetwork/jeo-plugin/pull/298
