### ISSUE TITLE
[ Story Map ] Editor story map - improvement UX

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#295]
**Story Map – visualização de slides**
Quando eu clico em um slide da lista de slides, a página no navegador vai para baixo, gerando um comportamento incômodo. Exemplo [aqui](https://onedrive.live.com/?cid=25675bc12936bef5&id=25675BC12936BEF5%21834915&ithint=video,mp4&authkey=!AMtOnOtlIV7L1lY).

**Comment by brunosmartin** [comment]
pouca descrição na tarefa e o link não está mais disponível
