### ISSUE TITLE
[ Story Map ] The map with id=985 broke the story map  (infoamazonia-jeo.hacklab.com.br)

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#296]
Map [985](https://infoamazonia-jeo.hacklab.com.br/maps/indice-de-progresso-social-na-amazonia/) 

- [x] If map 985 is used in story map, it throws an error console. The layer which generates this error is:
mapbox / infoamazonia/ckay6jiq40rkv1imctu2a8vcu

![image](https://user-images.githubusercontent.com/12487823/104533192-aee9c500-55f0-11eb-8c19-fee7716d1752.png)

https://infoamazonia-jeo.hacklab.com.br/storymap/story-dinci/

![image](https://user-images.githubusercontent.com/12487823/104532658-7f868880-55ef-11eb-8e2e-a00c9b67a398.png)

Story map with a map which has layer "indice social" only
https://infoamazonia-jeo.hacklab.com.br/storymap/story-map-con-indice-social/

**Comment by isaquemelo** [comment]
If a layer has a link inside its content(attribution). It will not be parsed correctly inside the `data-properties` breaking JSON enconding

![image](https://user-images.githubusercontent.com/7103838/104606031-04a88680-565e-11eb-8e3a-fdcfdaeb198a.png)

**Comment by isaquemelo** [comment]
PR: https://github.com/EarthJournalismNetwork/jeo-plugin/pull/301
