### ISSUE TITLE
[ Mapbox attribution ] Don't use compact=true

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#304]
### Requisito:
O ícone "i" não está de acordo com as diretrizes do Mapbox, como tenho dito, e "compact:true" não pode ser usado. Detalhes em https://docs.mapbox.com/mapbox-gl-js/api/markers/#attributioncontrol

Desta mesma página: "Attribution should not be collapsed if it can comfortably fit on the map. compact should only be used to modify default attribution when map size makes it impossible to fit default attribution and when the automatic compact resizing for default settings are not sufficient."

###Fix

**View Map**
- [x] Compact = false / Position: Bottom= right in Map in _Desktop_

![image](https://user-images.githubusercontent.com/12487823/106227482-02027100-61c8-11eb-8664-9a2b9a77ec1d.png)

- [x] Compact = true / Position: Bottom= left in Map in _Mobile_

![image](https://user-images.githubusercontent.com/12487823/106227685-645b7180-61c8-11eb-9fdd-cbd62d965d80.png)

**Embed Map**

- [x] Compact = false / Position: Bottom= right in Embed Map in _Desktop_

![image](https://user-images.githubusercontent.com/12487823/106227782-a2589580-61c8-11eb-839a-6e1f7e8412d8.png)
![image](https://user-images.githubusercontent.com/12487823/106227868-dfbd2300-61c8-11eb-989e-1bd16205e180.png)

- [x] Compact = true / Position: Bottom= left in Embed Map in _Mobile_ (in a post)

![image](https://user-images.githubusercontent.com/12487823/106228463-2cedc480-61ca-11eb-928b-9a6c8bdebe8d.png)

**Story Map**
- [x] Compact = false / Position: Bottom= right in Story Map  in _Desktop_

![image](https://user-images.githubusercontent.com/12487823/106232367-9d98df00-61d2-11eb-902f-54721d2fd213.png)

**New fixes**
- [x] Styles for attribution icon (white background is not aligned to 'i')
- [x] Compact attribution in Embed Map in Mobile mode

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-plugin/pull/310

**Comment by pamelars86** [comment]
In StoryMap mobile, attributtion is not visible
![image](https://user-images.githubusercontent.com/12487823/106232201-2b27ff00-61d2-11eb-962c-7117f6096e55.png)
