### ISSUE TITLE
[ Published Map ] Info popup doesn't show  layer's content when lang is EN or ES

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#316]
As descrições e botões de download e créditos de "info" não estão aparecendo nos mapas em espanhol e inglês: https://dev.infoamazonia.org/es/maps/deforestacion/, https://dev.infoamazonia.org/en/maps/ips/ (mas aparecem no mesmo mapa em pt)

Other Ex:https://dev.infoamazonia.org/en/maps/teste-caso-5/ tem em PT e EN. No PT funciona, no EN não

**Comment by isaquemelo** [comment]
Directly related to https://github.com/EarthJournalismNetwork/jeo-plugin/issues/317

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-plugin/pull/318
