### ISSUE TITLE
[ Embed Map ] Embed map for EN or ES shows message "Map doesn't have layer"

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#317]
Embed map for EN o ES map with layers is showing message "Map doesn't have layers"

Ex.
https://dev.infoamazonia.org/embed/?map_id=59755

![image](https://user-images.githubusercontent.com/12487823/106811617-5afd5980-664d-11eb-9af6-448ef014e01e.png)

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-plugin/pull/318
