### ISSUE TITLE
[ Layer ] Interaction over interaction

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#320]
- [x] Se há features sobrepostos no mapa, a interatividade hover está sobreponto. Deveria mostrar só o popup mais recente. 

![image](https://user-images.githubusercontent.com/12487823/107061999-90be5180-67b7-11eb-8529-e5f69dba50e4.png)

O mouse estava no ponto marcado com um X em vermelho. O que ocorre é que, se há features de tilesets distintos sobrepostas, dois popups vão aparecer, um sobreposto ao outro. O comportamento desejado é que o popup mostrado seja só o que o mouse passou mais recentemente, como temos no site atual. Exemplo do site atual aqui: https://infoamazonia.org/en/maps/deforestation/#!/story=post-61441&loc=-4.787205972686506,-62.7593994140625,9 (tem que ativar as duas camadas, de terra indígenas e áreas protegidas, para ver)

**Comment by isaquemelo** [comment]
Fix 1: https://github.com/EarthJournalismNetwork/jeo-plugin/tree/bugfix/hide-overlaping-popups
