### ISSUE TITLE
[ Embed Map ] Iframe has a padding-top

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#323]
Here: https://infoamazonia-jeo.hacklab.com.br/2021/02/10/nosso-planeta-terra/

![image](https://user-images.githubusercontent.com/12487823/107463308-8ea01e00-6b3c-11eb-8555-850fe8ecbbed.png)

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-plugin/pull/324
