### ISSUE TITLE
[ Layer ] Labels in layer are bigger when it is loaded as Raster instead of style

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#333]
_Warning
By default, the modern Static Tiles API returns a 512×512 map tile, instead of the 256×256 that Mapbox classic styles returned. If you do not include the tileSize: 512 and zoomOffset: -1 options, your map will still load but labels, icons, and other features may appear much smaller than expected._

Source: https://docs.mapbox.com/help/troubleshooting/

Layer: mapbox://styles/infoamazonia/ckamzgj211hqp1kqct1qh9h8w

![image](https://user-images.githubusercontent.com/12487823/109018853-366a2f80-7697-11eb-8f8b-386cc9f039ef.png)

**Comment by isaquemelo** [comment]
https://github.com/EarthJournalismNetwork/jeo-plugin/pull/335
