### ISSUE TITLE
[ Story Map ] Story Map Editor must reflect changes when order of map's layers has changed.

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#336]
Currently, only Front End is considering new order of map's layers

**Test:** Quando a ordem de layers é alterada no mapa que usa o Story Map

- No início a layer “Zonas mineras” está acima da layer “layer satélite verde”
- Depois, coloca-se a layer “Layer satelite verde” acima da layer “Zonas mineiras” no mapa que é usado no Story Map
- O Story map terá a nova ordem de layers no Front End e Back End

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-plugin/pull/344

**Comment by isaquemelo** [comment]
Rendered layer still in the wrong order

**Comment by isaquemelo** [comment]
> Rendered layer still in the wrong order

https://github.com/EarthJournalismNetwork/jeo-plugin/pull/344/commits/aea6714dd792299f5f8e9047db6607cbd4e400f0
