### ISSUE TITLE
[ Map Block ] Support wide width

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#339]
**Relato**
 se eu defino "largura ampla" para o mapa, ele não fica com largura ampla, mas com a mesma largura e alinhado à esquerda. Não importa o modelo selecionado nos atributos do post. Este é o post de teste: https://infoamazonia.org/wp-admin/post.php?post=84238&action=edit

![image](https://user-images.githubusercontent.com/12487823/109371087-f4e9a800-7881-11eb-9990-560c84cd8f87.png)

![image](https://user-images.githubusercontent.com/12487823/109371092-fdda7980-7881-11eb-9dd7-063692401ed8.png)

**Current Situation**
Funciona só com Largura Total

https://infoamazonia-jeo.hacklab.com.br/2020/08/27/latin-america-with-jeo/

**Possible fix**

![image](https://user-images.githubusercontent.com/12487823/109371629-8fe38180-7884-11eb-9901-a4b433de78dd.png)

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-plugin/pull/343
