### ISSUE TITLE
[ Published Map ] When Map Page is opened, map is shown in different location for few seconds

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#340]
*Relato do Stefano*

Algo que percebemos aqui: existe uma animação no carregamento dos mapas que é meio estranha. Eu não entendi a lógica ainda. Veja neste mapa: https://infoamazonia.org/maps/amazonia-minada-isolados/. Ele começa em lat, lon = 0 (ou seja, no cruzamento da linha do Equador com o Meridiano de Greenwich) e depois vai rapidinho para o lugar adequado. Por que não começar direto do lugar e nível de zoom adequados? Esta animação é tão rápida que mal dá tempo de carregar as features, então no final só gera uma experiência estranha pro usuário. Outros mapas também têm uma animação no início, mas não está claro se começa do mesmo lugar.
Amazônia Minada Isolados | InfoAmazonia

**Comment by isaquemelo** [comment]
gfix/remove-focus-animation

**Comment by isaquemelo** [comment]
PR https://github.com/EarthJournalismNetwork/jeo-plugin/pull/342

**Comment by isaquemelo** [comment]
When map has "Load interactions" set the fix is not working

**Comment by isaquemelo** [comment]
> When map has "Load interactions" set the fix is not working

https://github.com/EarthJournalismNetwork/jeo-plugin/pull/342/commits/4a4014a94882ae3327edec40ef688bc4bd8c7e9d
