### ISSUE TITLE
create layer metada map_attribution_link (URL) and make it editable in the right panel

### ISSUE THREAD

**Issue by brunosmartin** [EarthJournalismNetwork/jeo-plugin#38]
- [x] modificar posição do campo para antes do select de tipo de legenda

**Comment by rafaelchavesfreitas** [comment]
a posição do campo não ficou boa, vou modificar a descrição da issue com a localização do campo

**Comment by bwstefano** [comment]
Tested with [this layer](https://jeo.hacklab.com.br/wp-admin/post.php?post=129&action=edit) at [this post](https://jeo.hacklab.com.br/index.php/2020/03/22/lero-lero/) (the second map) and it isn't working properly. The admin interface has two fields: "Map source url download link" and "Map attribution link*". However, only the second becomes something at the bottom of the map, but it isn't a valid link.

I would assume one of the fields should the the link title and the other would the its URL.

Also none of these fields should be mandatory, so we need to remove the asterisk.

If the layer is added to a map from the maps library, nothing will show at all – [here's one example](https://jeo.hacklab.com.br/index.php/maps/pec-na-amazonia/).

**Comment by hockpond** [comment]
These fields aren't mandatory anymore. Also, I think the problem with Map attribution link not being a valid link has been fixed.

Talking about the function of "Map source url download link", it may be better to create another issue to change its behavior if needed. What do you think?
