### ISSUE TITLE
Fatal error: Uncaught Error: Undefined constant "ICL_LANGUAGE_CODE"

### ISSUE THREAD

**Issue by matheusgimenez** [EarthJournalismNetwork/jeo-plugin#394]
We need to apply the currentLang parameter conditionally. Easy to fix :)

**MORE INFORMATION**:
Fatal error: Uncaught Error: Undefined constant "ICL_LANGUAGE_CODE" in /var/www/html/wp-content/plugins/jeowp/includes/class-jeo.php:334

**Comment by bwstefano** [comment]
In [Pasifika Environews](https://pasifika.news/), that error made a critical error appear on all posts:

![image](https://user-images.githubusercontent.com/11841075/172446385-300ce5e1-a144-4695-8376-e50cd059bffa.png)

After some debugging, the developers noticed the issue was that

> There is no check for ICL_LANGUAGE_CODE before it runs this `wp_localize_script`. When I remove the line, there is no error
> https://github.com/EarthJournalismNetwork/jeo-plugin/blob/2.5.1/src/includes/class-jeo.php#L355

**Comment by bwstefano** [comment]
A little but more on this: that line adds compatibility with WPML, but Pasifika doesn't have it. With PHP 8, that fatal error broke the website. The problem probably won't happen under PHP 7.x or if the website uses WPML.

**Comment by bwstefano** [comment]
The release 2.5.3 solves the issue. However, I found another error, which might not be related to this issue. Whenever the plugin was updated already or is in version 2.5.1, if it is disabled, I won't be able to enable it again as it will produce the following error when doing so:

> Plugin could not be activated because it triggered a fatal error.
> 
> Fatal error: Cannot redeclare GuzzleHttp\describe_type() (previously declared in /var/www/html/wp-content/plugins/newspack-plugin/vendor/guzzlehttp/guzzle/src/functions.php:16) in /var/www/html/wp-content/plugins/jeowp/includes/integrations/aws/GuzzleHttp/functions.php on line 41

The installed version of the Newspack Plugin is 1.7.0. I had to disable it, enable the JEO WP plugin and only then enable Newspack Plugin again. This is the only way I found to keep both plugins active.
