### ISSUE TITLE
add option to set map preview zoom as initial, min or max

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [EarthJournalismNetwork/jeo-plugin#51]
- [x] max
- [x] min
- [x] initial

**Comment by hockpond** [comment]
The Max and Min options has been added.

**Comment by rafaelchavesfreitas** [comment]
- [ ] A ideia dos botões é mudar o zoom do preview do mapa sem modificar o valor do campo "Initial zoom". A ideia é que o usuário possa testar os valores definidos como zoom máximo e zoom mínimo sem alterar o valor do zoom inicial, e também voltar para o zoom inicial
- [ ] os botões da forma que estão não deixam claro para o que servem. sugiro colocar um botãozinho com aquele ícone de olho e tooltip dizendo "visualizar o zoom no preview do mapa", ou algo assim

ícone de olho: 
![image](https://user-images.githubusercontent.com/1181261/78154754-011b7a00-7413-11ea-8e96-dd1b83fdba94.png)

**Comment by bwstefano** [comment]
This setting shouldn't allow me to set a min zoom higher than the max zoom or the opposite. It shouldn't also allow me to set an initial zoom that isn't between min and max values.
