### ISSUE TITLE
add configuration to enable/disable zoom

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [EarthJournalismNetwork/jeo-plugin#55]

**Comment by leopiccionia** [comment]
Is it a duplicate of #46?

**Comment by bwstefano** [comment]
This setting should be labeled as:
"Disable zoom on post" -> "Disable scroll zoom on post"

Also zoom buttons should always appear on maps, like the map at https://dialogochino.net/31057-chinas-brazilian-beef-demand-linked-to-amazon-deforestation-risk/

**Comment by bwstefano** [comment]
If I mouse over the zoom buttons, the plus and minus signs disappear, when only their backgrounds should be turned gray. See below:

![IMG_20200515_190822_trim](https://user-images.githubusercontent.com/11841075/82100390-e4e04d80-96df-11ea-8d31-eadd12d9dba4.jpg)
