### ISSUE TITLE
enable map preview zoom and fullscreen buttons

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [EarthJournalismNetwork/jeo-plugin#57]
- [x] Zoom buttons

- [x] Fullscreen buttons

**Comment by rafaelchavesfreitas** [comment]
use fullscreen mode instead of modal:
https://docs.mapbox.com/mapbox-gl-js/example/fullscreen/

**Comment by rafaelchavesfreitas** [comment]
I could not find the fullscreen button:
![image](https://user-images.githubusercontent.com/1181261/79170742-a8f75700-7dc6-11ea-9d93-6e2b4ea901e8.png)

**Comment by hockpond** [comment]
It only appears on the post itself and on preview.

**Comment by hockpond** [comment]
I'll fix that, thanks.

**Comment by bwstefano** [comment]
Can we also have these buttons for maps added in posts? Such as at https://jeo.hacklab.com.br/wp-admin/post.php?post=327&action=edit

**Comment by bwstefano** [comment]
If I mouse over the zoom buttons, the plus and minus signs disappear, when only their backgrounds should be turned gray. See below:

![IMG_20200515_190822_trim](https://user-images.githubusercontent.com/11841075/82100390-e4e04d80-96df-11ea-8d31-eadd12d9dba4.jpg)
