### ISSUE TITLE
map related posts

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [EarthJournalismNetwork/jeo-plugin#58]
- [x] add a checkbox to display all posts
- [x] allow to remove start date and end date
- [x] do not display any posts if the filters are empty

**Comment by rafaelchavesfreitas** [comment]
- [ ] A ideia dos botões é mudar o zoom do preview do mapa sem modificar o valor do campo "Initial zoom". A ideia é que o usuário possa testar os valores definidos como zoom máximo e zoom mínimo sem alterar o valor do zoom inicial, e também voltar para o zoom inicial
- [ ] os botões da forma que estão não deixam claro para o que servem. sugiro colocar um botãozinho com aquele ícone de olho e tooltip dizendo "visualizar o zoom no preview do mapa", ou algo assim

ícone de olho: 
![image](https://user-images.githubusercontent.com/1181261/78154754-011b7a00-7413-11ea-8e96-dd1b83fdba94.png)

**Comment by rafaelchavesfreitas** [comment]
- checkbox to display all posts is missing
- button to remove date interval is not working
- I was unable to test if removing all filters results in a map without posts because I was unable to remove date interval.
- I don't understand the **show related posts** checkbox.

**Comment by bwstefano** [comment]
If I don't add any filter, no geotagged post will show up, which is good. However, if I add some filters, save changes, and then remove all filters again, all geotagged posts will appear, so I'm not being able to clear the map again.

I tested with the map at https://jeo.hacklab.com.br/wp-admin/post.php?post=268
