### ISSUE TITLE
[Layer Edit Page] Map attribution link field in Configuration: add a regex for domains

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#77]
### **USER TEST**
- In Layer Edit Page
- In "data attribution link", you enter i.e. "google.com"
- Save the layer, then enter to the layer again, and you should see "https://google.com"

![image](https://user-images.githubusercontent.com/12487823/83758233-1a75b800-a648-11ea-87b4-8031b79019c6.png)

The data attribution link checks that any text must have a domain format.

Other tests:
if "data attribution link" starts with '/'. Ex. "/my-url". The attribution name in the map published will have this url: http://jeo.hacklab.com.br/my-url".
if "data attribution link" doesnt' start with '/'. Ex.  "my-url".  The attribution name in the map published will have this url: http://jeo.hacklab.com.br/post-url/my-url.

The attribution name published appears here:
![image](https://user-images.githubusercontent.com/12487823/83792008-de0a8200-a670-11ea-8074-9c16aeffa172.png)

**Comment by bwstefano** [comment]
@pamelars86, please assist with what I should be looking at here.

**Comment by pamelars86** [comment]
@bwstefano 
This is the test:
- In Layer Edit Page
- In "data attribution link", you enter i.e. "google.com"
- Save the layer, then enter to the layer again, and you should see "https://google.com"

![image](https://user-images.githubusercontent.com/12487823/83758233-1a75b800-a648-11ea-87b4-8031b79019c6.png)

The data attribution link checks that any text must have a domain format.
