### ISSUE TITLE
[Geolocate this post Modal - Edit Post] UX - Review flow to add a point

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#79]
- Left side: A single tab for List. Delete option must be a button
- Right side (new structure for layout):
-- add new point at the top
-- Search field 
-- Map
-- Selected points

Icaro starts this card. We could ask him for more information

**Comment by bwstefano** [comment]
Can secondary pin points also appear gray on the map? So they would follow the same colors of the list of added points.
