### ISSUE TITLE
[Post Edit Page] Map's name isn't shown in the post page. It's not possible to recognize what map is used

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#83]
Some examples here:
https://developer.wordpress.org/block-editor/designers/block-design/

- [x] Map's name appears when user clicks on the JEO Map block or JEO One time block

**Comment by bwstefano** [comment]
This is a very good observation, @pamelars86. However, can we show the name in a different way? The way it currently is might make the user think the map's name will be shown below the map when the post is published.

**Comment by hockpond** [comment]
@bwstefano Do you have any suggestion about where the name could be displayed without making the user think the map's name will be shown on the post?

**Comment by bwstefano** [comment]
@hockpond, it might require some design work, but I think it could be something in between the [gray default placeholder](https://developer.wordpress.org/block-editor/designers/block-design/#placeholders) and the gray setup area Luiza proposed at the [design screens](https://projects.invisionapp.com/share/UMUH8CZFSD4#/screens/390789811). Or it could be moved to the block toolbar.

@pamelars86, perhaps we should set a call to discuss this and other topics related to design first.
