### ISSUE TITLE
[Post - Map] Add 'disable navigation' check

### ISSUE THREAD

**Issue by pamelars86** [EarthJournalismNetwork/jeo-plugin#87]

**Comment by bwstefano** [comment]
@pamelars86, can you please assist me to verify this issue? I'm not sure what to check here.

**Comment by bwstefano** [comment]
While with this setting I'm not able to navigate the map with a mouse, I'm still able to do that on touch devices. Is it possible to make this checkbox setting work with touch devices as well?
